version: '3.9'

services:
  builder:
    image: portfolio-builder:${APP_VERSION}
    container_name: portfolio-builder
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - NODE_ENV=production
    volumes:
      - ./dist:/usr/src/app/dist
